import {
  Home,
  Users,
  Settings,
  Shield,
  FileText,
  Folder,
  FolderOpen,
  Search,
  Plus,
  Minus,
  X,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ChevronsUp,
  ChevronsLeft,
  ChevronsRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Menu,
  MoreHorizontal,
  MoreVertical,
  Edit,
  Trash2,
  Copy,
  Download,
  Upload,
  ExternalLink,
  Link,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Bell,
  BellOff,
  Calendar,
  Clock,
  Mail,
  Phone,
  MapPin,
  Globe,
  Sun,
  Moon,
  Laptop,
  Monitor,
  Smartphone,
  Tablet,
  Server,
  Database,
  Cloud,
  CloudOff,
  Wifi,
  WifiOff,
  RefreshCw,
  RotateCcw,
  Save,
  Filter,
  SlidersHorizontal,
  LayoutGrid,
  LayoutList,
  Table,
  BarChart,
  BarChart2,
  LineChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Zap,
  Star,
  Heart,
  Bookmark,
  Flag,
  Tag,
  Tags,
  Hash,
  AtSign,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  CheckCircle,
  CheckCircle2,
  XCircle,
  MinusCircle,
  PlusCircle,
  CircleDot,
  Circle,
  Square,
  SquareCheck,
  Loader2,
  LogIn,
  LogOut,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  User,
  Building,
  Building2,
  Briefcase,
  CreditCard,
  Wallet,
  DollarSign,
  ShoppingCart,
  ShoppingBag,
  Package,
  Box,
  Archive,
  Inbox,
  Send,
  MessageSquare,
  MessageCircle,
  Command,
  Terminal,
  Code,
  Code2,
  FileCode,
  Braces,
  GitBranch,
  GitCommit,
  GitPullRequest,
  GitMerge,
  Layers,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  Expand,
  Shrink,
  Move,
  GripVertical,
  GripHorizontal,
  Image,
  ImagePlus,
  Camera,
  Video,
  Music,
  Play,
  Pause,
  StopCircle,
  SkipBack,
  SkipForward,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Headphones,
  Radio,
  Printer,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  ClipboardCopy,
  Paperclip,
  Pin,
  PinOff,
  Scissors,
  Pencil,
  PenTool,
  Highlighter,
  Palette,
  Droplet,
  Eraser,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List,
  ListOrdered,
  ListChecks,
  Quote,
  Type,
  Heading1,
  Heading2,
  Heading3,
  Text,
  TextCursor,
  FileUp,
  FileDown,
  FilePlus,
  FileMinus,
  FileSearch,
  FolderPlus,
  FolderMinus,
  FolderSearch,
  HardDrive,
  Cpu,
  MemoryStick,
  CircuitBoard,
  Plug,
  Power,
  PowerOff,
  Battery,
  BatteryLow,
  BatteryCharging,
  Gauge,
  Timer,
  TimerOff,
  Hourglass,
  AlarmClock,
  CalendarDays,
  CalendarCheck,
  CalendarX,
  CalendarPlus,
  Share,
  Share2,
  QrCode,
  Scan,
  ScanLine,
  Sparkles,
  Wand2,
  Bot,
  BrainCircuit,
  Lightbulb,
  Rocket,
  Target,
  Award,
  Trophy,
  Medal,
  Crown,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  type LucideIcon,
} from 'lucide-vue-next'

export const iconRegistry: Record<string, LucideIcon> = {
  home: Home,
  users: Users,
  settings: Settings,
  shield: Shield,
  'file-text': FileText,
  folder: Folder,
  'folder-open': FolderOpen,
  search: Search,
  plus: Plus,
  minus: Minus,
  x: X,
  close: X,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-down': ChevronsDown,
  'chevrons-up': ChevronsUp,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  menu: Menu,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  edit: Edit,
  pencil: Pencil,
  trash: Trash2,
  'trash-2': Trash2,
  delete: Trash2,
  copy: Copy,
  download: Download,
  upload: Upload,
  'external-link': ExternalLink,
  link: Link,
  eye: Eye,
  'eye-off': EyeOff,
  lock: Lock,
  unlock: Unlock,
  bell: Bell,
  'bell-off': BellOff,
  calendar: Calendar,
  clock: Clock,
  mail: Mail,
  email: Mail,
  phone: Phone,
  'map-pin': MapPin,
  location: MapPin,
  globe: Globe,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  server: Server,
  database: Database,
  cloud: Cloud,
  'cloud-off': CloudOff,
  wifi: Wifi,
  'wifi-off': WifiOff,
  refresh: RefreshCw,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  undo: RotateCcw,
  save: Save,
  filter: Filter,
  sliders: SlidersHorizontal,
  'layout-grid': LayoutGrid,
  grid: LayoutGrid,
  'layout-list': LayoutList,
  table: Table,
  'bar-chart': BarChart,
  'bar-chart-2': BarChart2,
  'line-chart': LineChart,
  'pie-chart': PieChart,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  activity: Activity,
  zap: Zap,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  flag: Flag,
  tag: Tag,
  tags: Tags,
  hash: Hash,
  'at-sign': AtSign,
  'alert-circle': AlertCircle,
  alert: AlertCircle,
  'alert-triangle': AlertTriangle,
  warning: AlertTriangle,
  info: Info,
  'help-circle': HelpCircle,
  help: HelpCircle,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  success: CheckCircle2,
  'x-circle': XCircle,
  error: XCircle,
  'minus-circle': MinusCircle,
  'plus-circle': PlusCircle,
  'circle-dot': CircleDot,
  circle: Circle,
  square: Square,
  'square-check': SquareCheck,
  'check-square': SquareCheck,
  checkbox: SquareCheck,
  loader: Loader2,
  loading: Loader2,
  spinner: Loader2,
  'log-in': LogIn,
  login: LogIn,
  'log-out': LogOut,
  logout: LogOut,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'user-check': UserCheck,
  'user-x': UserX,
  user: User,
  building: Building,
  'building-2': Building2,
  briefcase: Briefcase,
  'credit-card': CreditCard,
  wallet: Wallet,
  'dollar-sign': DollarSign,
  dollar: DollarSign,
  'shopping-cart': ShoppingCart,
  cart: ShoppingCart,
  'shopping-bag': ShoppingBag,
  package: Package,
  box: Box,
  archive: Archive,
  inbox: Inbox,
  send: Send,
  'message-square': MessageSquare,
  message: MessageSquare,
  'message-circle': MessageCircle,
  comment: MessageCircle,
  command: Command,
  terminal: Terminal,
  code: Code,
  'code-2': Code2,
  'file-code': FileCode,
  braces: Braces,
  'git-branch': GitBranch,
  'git-commit': GitCommit,
  'git-pull-request': GitPullRequest,
  'git-merge': GitMerge,
  layers: Layers,
  'panel-left': PanelLeft,
  sidebar: PanelLeft,
  'panel-right': PanelRight,
  'panel-top': PanelTop,
  'panel-bottom': PanelBottom,
  maximize: Maximize,
  minimize: Minimize,
  'maximize-2': Maximize2,
  fullscreen: Maximize2,
  'minimize-2': Minimize2,
  expand: Expand,
  shrink: Shrink,
  move: Move,
  drag: Move,
  'grip-vertical': GripVertical,
  'grip-horizontal': GripHorizontal,
  image: Image,
  'image-plus': ImagePlus,
  camera: Camera,
  video: Video,
  music: Music,
  play: Play,
  pause: Pause,
  stop: StopCircle,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  volume: Volume,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  mute: VolumeX,
  mic: Mic,
  'mic-off': MicOff,
  headphones: Headphones,
  radio: Radio,
  printer: Printer,
  print: Printer,
  clipboard: Clipboard,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'clipboard-copy': ClipboardCopy,
  paperclip: Paperclip,
  attachment: Paperclip,
  pin: Pin,
  'pin-off': PinOff,
  scissors: Scissors,
  cut: Scissors,
  'pen-tool': PenTool,
  highlighter: Highlighter,
  palette: Palette,
  droplet: Droplet,
  eraser: Eraser,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,
  'align-justify': AlignJustify,
  list: List,
  'list-ordered': ListOrdered,
  'list-checks': ListChecks,
  quote: Quote,
  type: Type,
  'heading-1': Heading1,
  'heading-2': Heading2,
  'heading-3': Heading3,
  text: Text,
  'text-cursor': TextCursor,
  'file-up': FileUp,
  'file-down': FileDown,
  'file-plus': FilePlus,
  'file-minus': FileMinus,
  'file-search': FileSearch,
  'folder-plus': FolderPlus,
  'folder-minus': FolderMinus,
  'folder-search': FolderSearch,
  'hard-drive': HardDrive,
  cpu: Cpu,
  'memory-stick': MemoryStick,
  'circuit-board': CircuitBoard,
  plug: Plug,
  power: Power,
  'power-off': PowerOff,
  battery: Battery,
  'battery-low': BatteryLow,
  'battery-charging': BatteryCharging,
  gauge: Gauge,
  timer: Timer,
  'timer-off': TimerOff,
  hourglass: Hourglass,
  'alarm-clock': AlarmClock,
  'calendar-days': CalendarDays,
  'calendar-check': CalendarCheck,
  'calendar-x': CalendarX,
  'calendar-plus': CalendarPlus,
  share: Share,
  'share-2': Share2,
  'qr-code': QrCode,
  scan: Scan,
  'scan-line': ScanLine,
  sparkles: Sparkles,
  magic: Sparkles,
  'wand-2': Wand2,
  wand: Wand2,
  bot: Bot,
  ai: Bot,
  'brain-circuit': BrainCircuit,
  lightbulb: Lightbulb,
  idea: Lightbulb,
  rocket: Rocket,
  target: Target,
  award: Award,
  trophy: Trophy,
  medal: Medal,
  crown: Crown,
  'thumbs-up': ThumbsUp,
  like: ThumbsUp,
  'thumbs-down': ThumbsDown,
  dislike: ThumbsDown,
  smile: Smile,
  happy: Smile,
  frown: Frown,
  sad: Frown,
  meh: Meh,
  neutral: Meh,
}

export function getIcon(name: string): LucideIcon | undefined {
  return iconRegistry[name.toLowerCase()]
}

export function registerIcon(name: string, icon: LucideIcon): void {
  iconRegistry[name.toLowerCase()] = icon
}

export function getIconNames(): string[] {
  return Object.keys(iconRegistry)
}
